### DISCUSSION TITLE
Custom lexer is used in production but not localhost. How to debug this?

### DISCUSSION THREAD

**Discussion by Andre601** [pygments/pygments#2669] [Q&A]
I'm currently encountering a rather strange behaviour that I cannot quite figure out.

When installing my custom lexer using `pip install .` (In the folder with the pyproject toml file), it is installed properly, but then using it (In my case through MkDocs and the PyMdownX Highlight extension) does not show the custom lexer.
However, when I push everything to then be published using GitHub Pages, the final pages do have the proper highlighting applied.

Is there some form of setting I need to change to allow custom lexers to work locally? Or is there perhaps a mistake I made?

Would apreciate assistance in getting this debugged...

**Comment by jeanas** [comment]
You'll need to show us your CI configuration and the commands you're using to run mkdocs locally. Most likely, you're running mkdocs from a Python environment different than the one you installed your plugin into.

**Reply by Andre601** [reply]
The workflow file used for publishing (where it works)
```yaml
name: Deploy Docs

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/publish_site.yml'
      - 'docs/**'
      - 'hooks/**'
      - 'theme/**'
      - 'mkdocs.yml'
      - 'requirements.txt'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false
  
jobs:
  buildAndDeploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          python -m pip install -r requirements.txt
      - name: Create Pygment lexer
        working-directory: hooks/CommandLexer/
        run: python -m pip install .
      - name: Build Docs
        run: mkdocs build
      - name: Configure Pages
        uses: actions/configure-pages@v4
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'site/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
```

And for local, I simple do `python -m pip install .` in the `hooks/CommandLexer/` folder, just like the action does, followed by `mkdocs serve`.

Perhaps the `serve` command is doing some things differently than the `build` command?
