### ISSUE TITLE
[BUG] Yaml highlights colons in a string as white

### ISSUE THREAD

**Issue by Yash-Singh1** [pygments/pygments#1972]
Given the following yaml:

```yaml
'Type: Bug / Error': 'bug/*'
'Type: Enhancement': 'feature/*'
'Type: Other': 'other/*'
```

The result is:

![Screenshot from 2021-11-24 14-07-13](https://user-images.githubusercontent.com/53054099/143318723-63a1e507-31a0-46de-b10b-d0fa0f2613e1.png)
