### ISSUE TITLE
SCSS parser doesn't recognize dollars

### ISSUE THREAD

**Issue by philippemilink** [pygments/pygments#2130]
Hello,

The Scss parser doesn't recognize the dollar sign. For example, in:
```scss
$base-color: #c6538c;
$border-dark: rgba($base-color, 0.88);

.alert {
  border: 1px solid $border-dark;
}
```
(from the documentation https://sass-lang.com/documentation/variables) the `$` in `border: 1px solid $border-dark;` is treated as an error (see also [here](https://pygments.org/demo/?lexer=scss&style=default&formatter=html&code=%24base-color%3A+%23c6538c%3B%0A%24border-dark%3A+rgba%28%24base-color%2C+0.88%29%3B%0A%0A.alert+%7B%0A++border%3A+1px+solid+%24border-dark%3B%0A%7D%0A)).
