### ISSUE TITLE
False error when lexing CSS

### ISSUE THREAD

**Issue by mgroth0** [pygments/pygments#2382]
Here is the CSS:

```css

.target-img {
  position: absolute; 
  top: 25%; 
  left: 50%; 
  transform: translate(-50%, -50%);
}

```

As you can see on https://pygments.org/demo/, the percent signs in the translate function are rendered as errors. But actually, they are valid CSS.
