### ISSUE TITLE
Highlight numbers and units in CSS dimensions as a whole?

### ISSUE THREAD

**Issue by TripleCamera** [pygments/pygments#2538]
Currently, in CSS [`<dimension>`](https://developer.mozilla.org/en-US/docs/Web/CSS/dimension)s, numbers and units are highlighted separately. Is it necessary to highlight them as a whole?

Some highlighting engines like Notepad++ and VS Code (using the default configuration) highlight them as a whole, while others do not.

Example:

```css
div {
    width: 100%;
    height: 100px;
}
```
