### ISSUE TITLE
wrong highlighting for yaml with comments ending with a colon (:)

### ISSUE THREAD

**Issue by DenisKuplyakov** [pygments/pygments#2652]
**What to do:**
1. Open demo: https://pygments.org/demo/
2. Select Language: YAML
3. Copy-paste the following:
    ```yaml
    {
      "foo": "foo",
       # foo:
      "bar": "bar",
       # baz: 0
      "baz": "baz",
       # baz
    }
    ```
4. Choose HTML formatter and lightbulb style.

**Observed behavior:**
![image](https://github.com/pygments/pygments/assets/3333218/1dbca7fd-87e6-4dcb-a0cd-032c5421cfc9)

**Expected behavior:**

1. First comment (foo) should be gray as other comments.
2. Second comment (baz) should be gray as other comments.
3. Highlighting of baz key is wrong.
