### ISSUE TITLE
Less: nesting, mixins, variables, &:extend()

### ISSUE THREAD

**Issue by verhovsky** [pygments/pygments#2689]
```less
div {
	.center;
	background-color: @primary-color;
}

ul {
	list-style-type: none;
	margin-top: 2em;

	li {
		background-color: #f00;
	}
}

ul {
	list-style-type: none;
	margin-top: 2em;

	li {
		background-color: red;

		&:hover {
		  background-color: blue;
		}

		a {
		  color: white;
		}
	}
}

.average(@x, @y) {
  @average-result: ((@x + @y) / 2);
}

div {
  .average(16px, 50px); // "call" the mixin
  padding: @average-result;    // use its "return" value
}


/*Extend is a way to share the properties of one selector with another. */

.display {
  height: 50px;
}

.display-success {
  &:extend(.display);
	border-color: #22df56;
}
```

https://pygments.org/demo/?lexer=less&style=solarized-light&formatter=html&code=div+%7B%0A%09.center%3B%0A%09background-color%3A+%40primary-color%3B%0A%7D%0A%0Aul+%7B%0A%09list-style-type%3A+none%3B%0A%09margin-top%3A+2em%3B%0A%0A%09li+%7B%0A%09%09background-color%3A+%23f00%3B%0A%09%7D%0A%7D%0A%0Aul+%7B%0A%09list-style-type%3A+none%3B%0A%09margin-top%3A+2em%3B%0A%0A%09li+%7B%0A%09%09background-color%3A+red%3B%0A%0A%09%09%26%3Ahover+%7B%0A%09%09++background-color%3A+blue%3B%0A%09%09%7D%0A%0A%09%09a+%7B%0A%09%09++color%3A+white%3B%0A%09%09%7D%0A%09%7D%0A%7D%0A%0A.average%28%40x%2C+%40y%29+%7B%0A++%40average-result%3A+%28%28%40x+%2B+%40y%29+%2F+2%29%3B%0A%7D%0A%0Adiv+%7B%0A++.average%2816px%2C+50px%29%3B+%2F%2F+%22call%22+the+mixin%0A++padding%3A+%40average-result%3B++++%2F%2F+use+its+%22return%22+value%0A%7D%0A%0A%0A%2F*Extend+is+a+way+to+share+the+properties+of+one+selector+with+another.+*%2F%0A%0A.display+%7B%0A++height%3A+50px%3B%0A%7D%0A%0A.display-success+%7B%0A++%26%3Aextend%28.display%29%3B%0A%09border-color%3A+%2322df56%3B%0A%7D%0A%0A
