### ISSUE TITLE
SourcesListLexer parses URI as components if options are present.

### ISSUE THREAD

**Issue by iBug** [pygments/pygments#2695]
Consider the following input:

```shell
deb http://deb.debian.org/debian bookworm main
deb [trusted=yes] http://deb.debian.org/debian bookworm main
```

Running `pygmentize -l debsources -f raw sources.list` produces the following result (comments added for clarity):

```shell
# Line 1
Token.Keyword   'deb'
Token.Text.Whitespace   ' '
Token.Literal.String    'http://deb.debian.org/debian'
Token.Text.Whitespace   ' '
Token.Keyword.Pseudo    'bookworm'
Token.Text.Whitespace   ' '
Token.Keyword.Pseudo    'main'
Token.Text      ''
Token.Text.Whitespace   '\n'

# Line 2
Token.Keyword   'deb'
Token.Text.Whitespace   ' '
Token.Literal.String.Other      '['
Token.Literal.String.Other      'trusted=yes'
Token.Literal.String.Other      ']'
Token.Text.Whitespace   ' '
Token.Keyword.Pseudo    'http://deb.debian.org/debian'
Token.Text.Whitespace   ' '
Token.Keyword.Pseudo    'bookworm'
Token.Text.Whitespace   ' '
Token.Keyword.Pseudo    'main'
Token.Text      ''
Token.Text.Whitespace   '\n'
```

Notice how on the second line the URI is parsed as `Pseudo` when it should be the same as the first line.

Additionally, it'd be great if the first word of the "components" part, which is "suites", would be parsed as something else so it distinguishes itself from the rest. I would like to see the second line parsed like this:

```yaml
# deb [trusted=yes] http://deb.debian.org/debian bookworm main
tokens:
  - keyword: "deb"
  - options: "[trusted=yes]"
  - uri: "http://deb.debian.org/debian"
  - suite: "bookworm"
  - components: "main"
```
