### ISSUE TITLE
Incomplete isolation of HTML with `full=False`

### ISSUE THREAD

**Issue by stefan6419846** [pygments/pygments#2735]
Formatting code as HTML with `full=False` does not generate completely isolated code.

Let's take the following example, which renders itself:

```python3
from pathlib import Path

from pygments import highlight
from pygments.formatters.html import HtmlFormatter
from pygments.lexers import guess_lexer_for_filename


path = Path(__file__)
formatter = HtmlFormatter(
    full=False, style='github-dark', linenos='inline', classprefix='pygments_', noclasses=False, cssclass='pygments_highlight'
)
lexer = guess_lexer_for_filename(path.name, path.read_text())

print(highlight(code=path.read_text(), lexer=lexer, formatter=formatter))

print(formatter.get_style_defs())
```

The limitations are most obvious from the generated stylesheet:

```css
pre { line-height: 125%; }
td.linenos .normal { color: #6e7681; background-color: #0d1117; padding-left: 5px; padding-right: 5px; }
span.linenos { color: #6e7681; background-color: #0d1117; padding-left: 5px; padding-right: 5px; }
td.linenos .special { color: #e6edf3; background-color: #6e7681; padding-left: 5px; padding-right: 5px; }
span.linenos.special { color: #e6edf3; background-color: #6e7681; padding-left: 5px; padding-right: 5px; }
.pygments_highlight .hll { background-color: #6e7681 }
.pygments_highlight .pygments_c { color: #8b949e; font-style: italic } /* Comment */
...
```

The following aspects seem to be a bit odd:

* The CSS will affect all `pre` elements of the page when embedded, while `.pygments_highlight pre { line-height: 125%; }` seems to be safer and actually uses the defined `cssclass`.
* Independent elements might clash with the `linenos` class as the `classprefix` is omitted here.
* The whole container misses any background color and thus might look odd. I added `.pygments_highlight { background-color: #0d1117; }` to my stylesheet to circumvent this.

Due to this behavior, I have to post-process both the CSS and HTML generated by *pygments*, while *pygments* already has the required values to avoid these issues.
