### ISSUE TITLE
LESS lexer marks nested `.`  and `h2` as invalid

### ISSUE THREAD

**Issue by stevepiercy** [pygments/pygments#2817]
With the following code sample, both the `.` and `h2` are marked as invalid by the LESS lexer. This can be reproduced in the [Pygments demo](https://pygments.org/demo/?lexer=less&style=bw&formatter=html&code=.highlight+%7B%0A++.highlight-header+%7B%0A++++display%3A+flex%3B%0A++++flex-direction%3A+column%3B%0A++++align-items%3A+center%3B%0A%0A++++h2+%7B%0A++++++text-align%3A+center%3B%0A++++++text-transform%3A+uppercase%3B%0A++++%7D%0A++%7D%0A%7D%0A).

```less
.highlight {
  .highlight-header {
    display: flex;
    flex-direction: column;
    align-items: center;

    h2 {
      text-align: center;
      text-transform: uppercase;
    }
  }
}
```

In the [Less Sandbox](https://www.lesstester.com/) there is no error.

See also:
- https://github.com/plone/volto/issues/5499
- https://github.com/pygments/pygments/issues/2606
