### ISSUE TITLE
WARNING: Lexing literal_block ... as "scss" resulted in an error at token: '$'

### ISSUE THREAD

**Issue by stevepiercy** [pygments/pygments#2818]
The following SCSS code block gets incorrectly marked as invalid.

```scss
$border-radius:               1rem;
.searchButton.btn.btn-secondary {
    border-radius: 0 $border-radius $border-radius 0;
}
```

[Pygments demo](https://pygments.org/demo/?lexer=scss&style=bw&formatter=html&code=%24border-radius%3A+++++++++++++++1rem%3B%0A.searchButton.btn.btn-secondary+%7B%0A++++border-radius%3A+0+%24border-radius+%24border-radius+0%3B%0A%7D%0A)

Compare on [Sass Playground](https://sass-lang.com/playground/#eJwzNFRJyi9KSS3SLUpMySwttlJABYZFqbnWXHrFqYlFyRlOpSUl+Xl6SSVgrFucmpyfl5JYVKlQzQVSi2aQgQKq0ehcA2uuWi4A1d4ocw==).

See https://github.com/plone/training/issues/870
